// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXl0L3VLyR8nmfRDE6ZYFc5PTNIFqMJzM',
    appId: '1:905502142591:web:b2368c283862cd12854f4a',
    messagingSenderId: '905502142591',
    projectId: 'chatappriverpod-7006a',
    authDomain: 'chatappriverpod-7006a.firebaseapp.com',
    storageBucket: 'chatappriverpod-7006a.appspot.com',
    measurementId: 'G-GP6HEKH8N0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4Auk-NWUiZpxMOG_0v_OUpVGOaCwKiOg',
    appId: '1:905502142591:android:d38a30871620a32e854f4a',
    messagingSenderId: '905502142591',
    projectId: 'chatappriverpod-7006a',
    storageBucket: 'chatappriverpod-7006a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQJYJGa7L_euJADSnT7nc2y7nNgacn2Fs',
    appId: '1:905502142591:ios:f351bd42899511bd854f4a',
    messagingSenderId: '905502142591',
    projectId: 'chatappriverpod-7006a',
    storageBucket: 'chatappriverpod-7006a.appspot.com',
    iosBundleId: 'com.example.whatasppflutterapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCQJYJGa7L_euJADSnT7nc2y7nNgacn2Fs',
    appId: '1:905502142591:ios:dc2d8b473cce15ba854f4a',
    messagingSenderId: '905502142591',
    projectId: 'chatappriverpod-7006a',
    storageBucket: 'chatappriverpod-7006a.appspot.com',
    iosBundleId: 'com.example.whatasppflutterapp.RunnerTests',
  );
}
